# Default values for deid-prep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/deid-prep
  pullPolicy: Always
  tag: 0.1.0
service:
  type: ClusterIP
  port: 8080

enabled: true

global:
  ingress:
    enabled:
    class:
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
    subdomain:

ingress:
  enabled: false
  class:
       # IBM: public-iks-k8s-nginx
       # Azure: addon-http-application-routing
       # AWS: nginx
  subdomain:

deid:
  url:

fhir:
  url:
  username: fhiruser
  password: integrati0n