{{- if .Values.enabled -}}
{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /{{ .Chart.Name }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "nifi-registry.fullname" . }}
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}