apiVersion: v1
kind: Service
metadata:
  name: {{ include "deid-prep.fullname" . }}
  labels:
    {{- include "deid-prep.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "deid-prep.fullname" . }}
  selector:
    {{- include "deid-prep.selectorLabels" . | nindent 4 }}