apiVersion: v1
kind: Service
metadata:
  name: {{ include "deid.fullname" . }}
  labels:
    {{- include "deid.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: deid-server-http
  selector:
    {{- include "deid.selectorLabels" . | nindent 4 }}
