apiVersion: v1
kind: Service
metadata:
  name: {{ include "fhir-trigger.fullname" . }}
  labels:
    {{- include "fhir-trigger.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: fhir-trigger
  selector:
    {{- include "fhir-trigger.selectorLabels" . | nindent 4 }}