# Default values for fhir.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/fhir-server-demo
  pullPolicy: IfNotPresent
  tag: everything-preview

service:
  type: ClusterIP
  httpPort: 80
  httpsPort: 443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

proxy:
  enabled: false
  image:
    repository: alvearie/fhir-proxy
    pullPolicy: IfNotPresent
    tag: 0.0.1
  service:
    port: 81
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi

notifications:
  kafka:
    enabled: false
    topicName: ""
    bootstrapServers: ""
    password: ""

bulkExportConfig:
    cosBucketName: fhir-r4-connectathon
    cosLocation: us
    cosEndpointInternal: fake
    cosApikey: fake
    cosSrvinstid: fake
    batchUserPw: change-password

initContainers:
  # fhir-init:  # <- will be used as container name
  #  image: "busybox:1.30.1"
  #  imagePullPolicy: "IfNotPresent"
  #  command: ['sh', '-c', 'echo this is an initContainer']
  #    volumeMounts:
  #    - mountPath: /tmp/foo
  #      name: foo

extraVolumeMounts: []

extraVolumes: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

nodeSelector: {}

tolerations: []

affinity: {}

env: []
# Example:
# - name: FHIR_TRANSACTION_MANAGER_TIMEOUT
#   value: '300s'
