apiVersion: v1
data:
  fhirserver.url: "http://ingestion-fhir/fhir-server/api/v4"
  fhirserver.username: "fhiruser"
  fhirserver.password: "integrati0n"
  pv.path: "/mnt/data/"
kind: ConfigMap
metadata:
  name: terminology-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terminology-mappings-pv-claim
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: terminology-mappings-pv-2
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-terminology-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ingestion-terminology-microservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ingestion-terminology-microservice
    spec:
      securityContext:
        runAsUser: 0


