{{- if .Values.enabled -}}
{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.service.httpPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cohort-service-ingress
  namespace: {{ .Release.Namespace }}
  {{- with index .Values "cohort-service" "labels" }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | default .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}-{{ .Release.Name }}-cohort-service.{{ .Values.global.ingress.subdomain | default .Values.ingress.subdomain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-cohort-service
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}