{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.service.httpPort -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cohort-service-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cohort-service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}.cohort-service.{{ .Values.ingress.subdomain }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-cohort-service
              servicePort: {{ $ingressPort }}
{{- end }}