apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "term-services-prep.fullname" . }}-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Mi
  hostPath:
    path: /mnt/data
  storageClassName: ibmc-vpc-block-10iops-tier