apiVersion: v1
kind: Service
metadata:
  name: {{ include "cql-bulk-export.fullname" . }}
  labels:
    {{- include "cql-bulk-export.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: {{ include "cql-bulk-export.fullname" . }}
  selector:
    {{- include "cql-bulk-export.selectorLabels" . | nindent 4 }}
