apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kafka-helper.fullname" . }}
  labels:
    {{- include "kafka-helper.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-helper.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "kafka-helper.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: kafka-helper
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        env:
          - name: KAFKAUSER
            value: token
          - name: KAFKAPW
            value: integrati0n
          - name: KAFKABOOTSTRAP
            value: {{ .Release.Name }}-kafka:9092
