kind: Deployment
apiVersion: apps/v1
metadata:
  name: snomed-to-icd10
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: snomed-to-icd10
  template:
    metadata:
      labels:
        app.kubernetes.io/name: snomed-to-icd10
    spec:
      containers:
        - name: snomed-to-icd10
          image: alvearie/snomed-to-icd10:0.0.1
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
          restartPolicy: Never
          env:
          - name: STORAGE_HOSTNAME
            value: "k8ssandra-dc1-stargate-service"
          - name: STORAGE_USERNAME
            value: "k8ssandra-superuser"
          - name: STORAGE_PASSWORD
            value: ""
          - name: INDEX_SEARCH_HOSTNAME
            value: "elasticsearch"
# Uncomment/Update the lines below to deploy the "Direct" API
#        - name: COS_ENDPOINT
#          value: "https://s3.us-east.cloud-object-storage.appdomain.cloud"
#        - name: COS_BUCKET_LOCATION
#          value: "US"
#        - name: COS_SERVICE_CRN
#          value: ""
#        - name: COS_API_KEY_ID
#         value: ""
#        - name: COS_AUTH_ENDPOINT
#          value: "https://iam.cloud.ibm.com/identity/token"
#        - name: COS_BUCKET_NAME
#          value: "fhir-term-graph"
---
kind: Service
apiVersion: v1
metadata:
  name: snomed-to-icd10
  labels:
    app.kubernetes.io/name: snomed-to-icd10
spec:
  ports:
    - name: snomed-to-icd10
      protocol: TCP
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: snomed-to-icd10
  type: ClusterIP
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: snomed-to-icd10
  labels:
    app.kubernetes.io/name: snomed-to-icd10
  annotations:
    kubernetes.io/ingress.class: public-iks-k8s-nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: <<HOSTNAME>>
      http:
        paths:
          - path: /snomed-to-icd10(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: snomed-to-icd10
                port:
                  number: 8080