# Default values for nlp-insights.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/nlp-insights
  pullPolicy: Always
  tag: 0.0.1

service:
  type: ClusterIP
  port: 5000

enabled: true

global:
  ingress:
    enabled:
    class:
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
    subdomain:

ingress:
  enabled: false
  class:
       # IBM: public-iks-k8s-nginx
       # Azure: addon-http-application-routing
       # AWS: nginx
  subdomain: