# In the short term, we are using the OpenJDK for UBI. Long term, we will use
# the IBM Java Small Footprint JVM (SFJ) for UBI, but that is not in public
# Docker at the moment.
FROM adoptopenjdk/openjdk8:ubi

LABEL maintainer="IBM Java Engineering at IBM Cloud"

RUN yum -y install --disableplugin=subscription-manager maven \
    && yum --disableplugin=subscription-manager clean all


ARG bx_dev_user=root
ARG bx_dev_userid=1000
RUN BX_DEV_USER=$bx_dev_user
RUN BX_DEV_USERID=$bx_dev_userid
RUN if [ $bx_dev_user != "root" ]; then useradd -ms /bin/bash -u $bx_dev_userid $bx_dev_user; fi
