# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build Core Services
      # The NARs depend on Core Servies hence the "install" here so the JARs are available in the local .m2 repo
      run: mvn --batch-mode --update-snapshots install --file services/pom.xml
    - name: Build NARs
      run: mvn --batch-mode --update-snapshots package --file nifi-processors/nifi-health-patterns-bundle/pom.xml
    - name: Build Cohort Service
      run: mvn --batch-mode --update-snapshots package --file cohort-service/pom.xml
      env:
        # This build depends on the Alvearie cohort's team repository so the token is needed to access that
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      