# Default values for fhir-data-quality.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/fhir-data-quality
  pullPolicy: Always
  tag: 0.1.1
service:
  type: ClusterIP
  port: 5000

enabled: true

ingress:
  enabled: false
  class: public-iks-k8s-nginx
  hostname:

requestTimeout: 30