# To run this action locally in your dev env:
#   docker run -v {full-path-to-folder-with-Dockerfile}:/tmp replicated/dockerfilelint /tmp/Dockerfile

name: Lint Docker

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Lint Docker Cohort Service Image 
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: cohort-service/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint Docker NiFi Custom Processors Image 
        uses: luke142367/Docker-Lint-Action@v1.1.1
        with:
          target: nifi-processors/Dockerfile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}