---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fhir.fullname" . }}-config
  labels:
    app: {{ include "fhir.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
{{ (tpl (.Files.Glob "config/*").AsConfig . ) | indent 2 }}
binaryData:
{{ range $path, $bytes := .Files.Glob (printf "binary-config/**")}}
{{ $name := base $path }}
{{- sha256sum (printf "%s/%s" (index (regexSplit "binary\\-config" (dir $path) -1) 1 ) $name ) | indent 2 }}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
{{ end }}
