# Default values for ascvd-from-fhir.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/expose-kafka
  pullPolicy: Always
  tag: 0.0.1
service:
  type: ClusterIP
  port: 5000

enabled: true
username: token
password: integrati0n
# bootstrap:

ingress:
  enabled: true
  class: REQUIRED-NOT-USED
       # IBM: public-iks-k8s-nginx
       # Azure: addon-http-application-routing
       # AWS: nginx
  subdomain: REQUIRED-NOT-USED