# Default values for ascvd-from-fhir.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: dlranum/kafkahelper
#alvearie/kafka-helper
  pullPolicy: Always
  tag: 0.1.0
service:
  type: ClusterIP
  port: 5000

enabled: true

ingress:
  enabled: true
  class: BAD
       # IBM: public-iks-k8s-nginx
       # Azure: addon-http-application-routing
       # AWS: nginx
  subdomain: BAD