apiVersion: apps/v1
kind: Deployment
metadata:
  name: whp-text-analytics-deployment
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: app
        image: <replace with docker user id>/whpa-text-analytics-service:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: text-analytics-config-pv-claim
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: text-analytics-config-pv
spec:
  storageClassName: ibmc-vpc-block-10iops-tier
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---