apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cql-bulkexport.fullname" . }}
  labels:
    {{- include "cql-bulkexport.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cql-bulkexport.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cql-bulkexport.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: cql-bulkexport
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP
        env:
          - name: FHIR_ENDPOINT
            value: {{ .Values.fhirendpoint }}
          - name: FHIRUSER
            value: {{ .Values.fhiruser }}
          - name: FHIRPW
            value: {{ .Values.fhirpw }}
          - name: COHORT_ENDPOINT
            value: {{ .Values.cohortendpoint }}
          - name: COS_ENDPOINT
            value: {{ .Values.cosendpoint }}
          - name: COS_API_KEY
            value: {{ .Values.cosapikey }}
          - name: COS_INSTANCE_CRN
            value: {{ .Values.cosinstancecrn }}
          - name: BUCKET_NAME
            value: {{ .Values.bucketname }}
          - name: RESOURCE_LIST
            value: {{ .Values.resourcelist }}
