# Default values for term-services-prep.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/term-services-prep
  pullPolicy: Always
  tag: 0.1.0
service:
  type: ClusterIP
  port: 8080

enabled: true

ingress:
  enabled: false
  class: public-iks-k8s-nginx
  hostname:

fhir:
  url:
  username: fhiruser
  password: integrati0n