# Default values for expose-kafka.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: alvearie/expose-kafka
  pullPolicy: Always
  tag: 0.0.25
service:
  type: ClusterIP
  port: 5000

enabled: true
username: token
password: integrati0n
inittopics:
inittopicnumpartitions:
inittopicreplication:
# bootstrap:
requestTimeout: 30

ingress:
  enabled: false
  class: public-iks-k8s-nginx
  hostname:
