---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "nifi-registry.fullname" . }}-config
  labels:
    app: {{ include "nifi-registry.name" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
data:
{{ (tpl (.Files.Glob "config/*").AsConfig . ) | indent 2 }}
