apiVersion: v1
kind: Service
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: nifi-registry
      protocol: TCP
      name: nifi-registry
  selector:
    {{- include "nifi-registry.selectorLabels" . | nindent 4 }}