apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "cert-secret-generator.fullname" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
      - list
      - watch
      - update
      - create
    apiGroups:
      - ''
    resources:
      - secrets