{{- if .Values.global.ingress.enabled -}}
{{- if .Values.fhir.enabled -}}
{{- $ingressPort := .Values.fhir.service.httpPort -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-fhir-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.fhir.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    ingress.kubernetes.io/proxy-read-timeout: '90'
    kubernetes.io/ingress.class: public-iks-k8s-nginx
spec:
  rules:
    - host: {{ .Release.Namespace }}.{{ .Release.Name }}-fhir.{{ .Values.global.ingress.subdomain}}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-fhir
              servicePort: {{ $ingressPort }}
{{- end }}
{{- end }}