{{- if .Values.ingress.enabled -}}
{{- if index .Values "cohort-service" "enabled" -}}
{{- $ingressPort := index .Values "cohort-service" "service" "httpPort" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-cohort-service-ingress
  namespace: {{ .Release.Namespace }}
  {{- with index .Values "cohort-service" "labels" }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
	    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
spec:
  rules:
    - host: {{ .Release.Namespace }}.{{ .Release.Name }}-cohort-service.{{ .Values.ingress.subdomain}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-cohort-service
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}
