apiVersion: v2
name: health-patterns
description: A Helm Chart to deploy the Alvearie Health Patterns reference implementations for clinical data ingestion and enrichment.

type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.8.2

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: s7

icon: https://avatars3.githubusercontent.com/u/72946463?s=200&v=4
keywords:
  - ibm
  - fhir
  - nifi
  - ingestion
  - enrichment
  - health records
  - clinical data
  - alvearie

home: https://github.com/Alvearie/health-patterns/helm-charts/health-patterns

maintainers:
  - name: Adam T. Clark
    email: atclark@us.ibm.com
  - name: David Ranum
    email: dlranum@us.ibm.com
  - name: Luis A. Garcia
    email: luisg@us.ibm.com

dependencies:
  - name: ibm-fhir-server
    alias: fhir
    version: 0.5.0
    condition: fhir.enabled
    repository: https://alvearie.io/alvearie-helm
  - name: term-services-prep
    version: 0.1.0
    condition: fhir.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: fhir-trigger
    version: 0.1.0
    condition: fhir-trigger.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: ibm-fhir-server
    version: 0.5.0
    condition: fhir-deid.enabled
    alias: fhir-deid
    repository: https://alvearie.io/alvearie-helm
  - name: fhir-trigger
    version: 0.1.0
    condition: fhir-deid-trigger.enabled
    alias: fhir-deid-trigger
    repository: https://alvearie.github.io/health-patterns/charts
  - name: deid
    version: 1.0.1
    condition: deid.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: deid-prep
    version: 0.1.0
    condition: deid.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: cohort-service
    version: 1.0.1
    condition: cohort-service.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: nifi-registry
    version: 0.1.0
    condition: nifi-registry.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: ascvd
    version: 0.1.0
    condition: ascvd.enabled
    repository: https://alvearie.github.io/health-analytics/charts
  - name: ascvd-from-fhir
    version: 0.1.0
    condition: ascvd.enabled
    repository: https://alvearie.github.io/health-analytics/charts

# Old Nifi
  - name: zookeeper
    version: 6.0.0
    condition: nifikop.disabled, zookeeper.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: nifi
    version: 0.6.0
    condition: nifikop.disabled, nifi.enabled
    repository: https://cetic.github.io/helm-charts

# New Nifi via NifiKop
  - name: zookeeper
    alias: zookeeper2
    version: 7.4.5
    condition: nifikop.enabled, zookeeper2.enabled
    repository: https://charts.bitnami.com/bitnami

  - name: kafka
    version: 12.1.0
    condition: kafka.enabled
    repository: https://charts.bitnami.com/bitnami
  - name: expose-kafka
    version: 0.2.1
    condition: kafka.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: cql-bulk-export
    version: 0.1.0
    condition: cql-bulk-export.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: nlp-insights
    version: 0.1.0
    condition: nlp-insights.enabled
    repository: https://alvearie.github.io/health-patterns/charts
  - name: kube-prometheus-stack
    version: 12.0.4
    condition: kube-prometheus-stack.enabled
    repository: https://prometheus-community.github.io/helm-charts
  - name: hl7-resource-generator
    version: 0.1.1
    condition: hl7-resource-generator.enabled
    repository: https://alvearie.github.io/hl7-resource-generator-service/chart
