global:
  ingress:
    enabled: true
    class: public-iks-k8s-nginx
         # IBM: public-iks-k8s-nginx
         # Azure: addon-http-application-routing
         # AWS: nginx
    subdomain: wh-health-patterns.dev.watson-health.ibm.com