{{- if .Values.enabled -}}
{{- if .Values.global.ingress.enabled -}}
{{- $ingressPort := index .Values "kube-prometheus-stack" "grafana" "service" "portName" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | default .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}-{{ .Release.Name }}-grafana.{{ .Values.global.ingress.subdomain | default .Values.ingress.subdomain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-grafana
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}
