{{- if .Values.enabled -}}
{{- if .Values.global.ingress.enabled -}}
{{- $ingressPort := .Values.nifi.service.httpInputPort -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-nifi-http-post-ingress
  namespace: {{ .Release.Namespace }}
  {{- with .Values.nifi.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.global.ingress.class | default .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}-{{ .Release.Name }}-nifi-http-post.{{ .Values.global.ingress.subdomain | default .Values.ingress.subdomain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: alvearie-nifi
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}
