{{- if .Values.deid.enabled -}}
{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.deid.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-deid
  namespace: {{ .Release.Namespace }}
  {{- with .Values.deid.labels }}
  labels:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/$1
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /deid(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-deid
                port: 
                  number: {{ $ingressPort }}
{{- end }}
{{- end }}