{{- if .Values.ingestion.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: nifi-ingestion-parameter-secret
type: Opaque
stringData:
  FHIR_UserPwd_PatientAccess: {{ .Values.fhir.fhirUserPassword }}
  FHIR_UserPwd_ProviderDirectory: {{ .Values.fhir.fhirUserPassword }}
  kafka.auth.password: {{ .Values.kafka.password }}
{{- end }}
