{{- if .Values.nifikop.enabled -}}
{{- if .Values.nifi2.enabled -}}
{{- if .Values.ingestion.enabled -}}
apiVersion: nifi.orange.com/v1alpha1
kind: NifiParameterContext
metadata:
  name: ingestion-parameter-context
  namespace: {{ .Release.namespace }}
spec:
  description: Ingestion Parameter Context
  clusterRef:
    name: nifi
    namespace: {{ .Release.namespace }}
  secretRefs:
    - name: nifi-ingestion-parameter-secret
      namespace: {{ .Release.namespace }}
  parameters:
    - name: FHIR_URL_PatientAccess
      value: http://{{ .Release.Name }}-fhir/fhir-server/api/v4
      description: FHIR api for patient access

    - name: FHIR_URL_ProviderDirectory
      value: http://{{ .Release.Name }}-fhir/fhir-server/api/v4
      description: FHIR api for provider

    - name: FHIR_User_PatientAccess
      value: fhiruser
      description : FHIR server user for Patient Access FHIR URL

    - name: kafka.brokers
      value: {{ .Release.Name }}-kafka:9092
      description: Comma-delimited list of brokers for eventstream instance

    - name: HL7_RESOURCE_GENERATOR_URL
      value: http://{{ .Release.Name }}-hl7-resource-generator:8080/hl7/transformation

    - name: ingest.topic.in
      value: ingest.topic.in
      description: Topic ingestion to accept requests from

    - name: ingest.topic.out
      value: ingest.topic.out
      description: Topic ingestion to post output to

    - name: ingest.topic.failure
      value: ingest.topic.failure
      description: Filter used for error topics

    - name: FHIR_User_ProviderDirectory
      value: fhiruser
      description: FHIR server user for Provider Directory FHIR URL

    - name: kafka.auth.user
      value: token
      description: CMSIOP Eventstream user id

    - name: maxResourcesInBundle
      value: "20"
      description: The maximum number of resources to add to a bundle for when autobundling is enabled.

    - name: kafka.consumer.group
      value: Clinical_Ingestion_Group
      description: Consumer group used by the pipeline adapters in environment specified

    - name: enrich.topic.in
      value: enrich.topic.in

    - name: enrich.topic.out
      value: enrich.topic.out

    - name: enrich.topic.failure
      value: enrich.topic.failure
{{- end }}
{{- end }}
{{- end }}