name: Updates to nlp insights

# on:
#   pull_request:
#     branches: [ main ]

# Environment variables available to all jobs and steps in this workflow
# env:
#   GITHUB_SHA: ${{ github.sha }}
#   IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
#   ACD_API_KEY: ${{ secrets.ACD_API_KEY }}
#   DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
#   IBM_CLOUD_REGION: us-east
#   CLUSTER_NAMESPACE: github
#   FHIR_IP: github.wh-health-patterns.dev.watson-health.ibm.com/fhir
#   FHIR_DEID_IP: github.wh-health-patterns.dev.watson-health.ibm.com/fhir-deid
#   NIFI_IP: github.wh-health-patterns.dev.watson-health.ibm.com/
#   DEID_IP: github.wh-health-patterns.dev.watson-health.ibm.com/deid
#   EXP_KAFKA_IP: github.wh-health-patterns.dev.watson-health.ibm.com/expose-kafka
#   ASCVD_FROM_FHIR_IP: github.wh-health-patterns.dev.watson-health.ibm.com/ascvd-from-fhir
#   TERM_PREP_IP: github.wh-health-patterns.dev.watson-health.ibm.com/term-services-prep
#   DEID_PREP_IP: github.wh-health-patterns.dev.watson-health.ibm.com/deid-prep
#   NLP_INSIGHTS_IP: github.wh-health-patterns.dev.watson-health.ibm.com/nlp-insights


on:
 pull_request:
  paths:
  - services/nlp-insights/text_analytics/app.py

jobs:
  SimpleTestDevFlow:
    name: Dev flow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2


    - name: SimpleEcho
      run: |
        echo "Change to the app.py"

    - name: Read Helm Chart
      id: chart
      uses: jacobtomlinson/gha-read-helm-chart@master
      with:
        path: services/nlp-insights/chart

    - name: Print outputs
      run: |
        echo "Name - ${{ steps.chart.outputs.name }}"
        echo "Version - ${{ steps.chart.outputs.version }}"
        echo "App Version - ${{ steps.chart.outputs.appVersion }}"

    - name: Cat the file
      run: |
        cat services/nlp-insights/text_analytics/app.py

    - name: Generate build ID
      id: prep
      run: |
#          branch=${GITHUB_REF##*/}
#          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${ts}"

    - name: Print id
      run: |
        echo "dlranum/nlp-insights:${{ steps.prep.outputs.BUILD_ID }}"
