name: Updates to nlp insights

# on:
#   pull_request:
#     branches: [ main ]

# Environment variables available to all jobs and steps in this workflow
# env:
#   GITHUB_SHA: ${{ github.sha }}
#   IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
#   ACD_API_KEY: ${{ secrets.ACD_API_KEY }}
#   DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}
#   IBM_CLOUD_REGION: us-east
#   CLUSTER_NAMESPACE: github
#   FHIR_IP: github.wh-health-patterns.dev.watson-health.ibm.com/fhir
#   FHIR_DEID_IP: github.wh-health-patterns.dev.watson-health.ibm.com/fhir-deid
#   NIFI_IP: github.wh-health-patterns.dev.watson-health.ibm.com/
#   DEID_IP: github.wh-health-patterns.dev.watson-health.ibm.com/deid
#   EXP_KAFKA_IP: github.wh-health-patterns.dev.watson-health.ibm.com/expose-kafka
#   ASCVD_FROM_FHIR_IP: github.wh-health-patterns.dev.watson-health.ibm.com/ascvd-from-fhir
#   TERM_PREP_IP: github.wh-health-patterns.dev.watson-health.ibm.com/term-services-prep
#   DEID_PREP_IP: github.wh-health-patterns.dev.watson-health.ibm.com/deid-prep
#   NLP_INSIGHTS_IP: github.wh-health-patterns.dev.watson-health.ibm.com/nlp-insights


on:
 pull_request:
  paths:
  - services/expose-kafka/exposekafka.py

jobs:
  SimpleTestDevFlow:
    name: Dev flow
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2


    - name: SimpleEcho
      run: |
        echo "Change to the exposekafka.py"

    - name: Read Helm Chart
      id: chart
      uses: jacobtomlinson/gha-read-helm-chart@master
      with:
        path: services/expose-kafka/chart

    - name: Print outputs
      run: |
        echo "Name - ${{ steps.chart.outputs.name }}"
        echo "Version - ${{ steps.chart.outputs.version }}"
        echo "App Version - ${{ steps.chart.outputs.appVersion }}"

    - name: Cat the file
      run: |
        cat services/expose-kafka/exposekafka.py

    - name: Generate tag
      id: prep
      run: |
          ts=$(date +%s)
          echo "::set-output name=TAG::${ts}"

    - name: Print id
      run: |
        echo "${{ steps.prep.outputs.TAG }}"

    - name: Change dir
      run: |
        cd services/expose-kafka

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DLR_DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DLR_DOCKERHUB_USERNAME }} --password-stdin

    - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: dlranum/expose-kafka:${{steps.prep.outputs.tag}}

    # - name: Build the tagged Docker image
    #   run: docker build  -t dlranum/expose-kafka:${{steps.prep.outputs.tag}} -f Dockerfile
    # - name: Push the tagged Docker image
    #   run: docker push dlranum/expose-kafka:${{steps.prep.outputs.tag}}

    - name: Update values yaml
      run: |
        sed -i .old  "s@tag:.*@tag: ${{steps.prep.outputs.tag}}@" values.yaml
        sed -i .old  "s@repository:.*@repository: ${{steps.prep.outputs.tag}}@" values.yaml
        cat values.yaml
