name: Java CI

on: 
  push:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package --file cohort-service/pom.xml
    - name: Run unit test with Surefire
      run: mvn test
    - name: Build Cohort Service Docker	
      run: docker build cohort-service -t atclark/cohort-service:SNAPSHOT
      env:
        # This build depends on the Alvearie cohort's team repository so the token is needed to access that
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Cohort Service Docker	
      run: docker push atclark/cohort-service:SNAPSHOT