name: Java CI

on: 
  push:
    paths:
    - '.github/workflows/expose-kafka*'
    - 'services/expose-kafka/**'
    - 'scripts/expose-kafka*'

jobs:
#  build:
#    name: Build Expose-Kafka
#    runs-on: ubuntu-latest
  docker:
    name: Build and Push Expose-Kafka Docker Container 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: atclark/expose-kafka


#    - name: Build and push Docker image
#      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#      with:
#        context: services/expose-kafka
#        push: true
#        tags: ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}

    - name: aTc script
      run: ./scripts/expose-kafka-build.sh \
	-r=atclark \
	-n=expose-kafka \
	-t=SNAPSHOT \
	-v=${{steps.meta.outputs.version}} \
	-a=${{steps.meta.outputs.tags}} \
	-l=${{steps.meta.outputs.labels}} \
	-j=${{steps.meta.outputs.json}} \
	-b=${{steps.meta.outputs.bake-file}} 

#    - name: Push Expose-Kafka Docker Container	
#      run: docker push ${{github.actor}}/expose-kafka:SNAPSHOT