name: Java CI

on: 
  push:
    paths:
    - '.github/workflows/expose-kafka*'
    - 'services/expose-kafka/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Expose-Kafka Docker container	
      run: docker build services/expose-kafka -t atclark/expose-kafka:SNAPSHOT
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push Expose-Kafka Docker Container	
      run: docker push atclark/expose-kafka:SNAPSHOT