name: Java CI

on:
  push:
    paths:
    - '.github/workflows/expose-kafka*'
    - 'services/expose-kafka/**'
    - 'scripts/expose-kafka*'
    inputs:
      environment:
        description: 'Define env name'
        required: true
        default: 'prod'


jobs:
#  build:
#    name: Build Expose-Kafka
#    runs-on: ubuntu-latest
  docker:
    name: Build and Push Expose-Kafka Docker Container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run build script
      run: ./scripts/expose-kafka-build.sh -n=expose-kafka -r=${{ .DOCKER_HUB_USERNAME }} --debug
      inputs:
        numOctocats:
         description: 'Number of Octocats'
         required: false
         default: '1'
