name: Expose Kafka Continuous Integration

on:
  push:
    paths:
    - '.github/workflows/expose-kafka*'
    - 'services/expose-kafka/**'


jobs:
  docker:
    name: Build all Expose-Kafka artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run build script
      run: |
        .github/workflows/scripts/build-service.sh \
          -r=expose-kafka 
          -m=PUSH 
          --docker-user=${{ secrets.DOCKER_HUB_USERNAME }} 
          --docker-token=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 
          --private-docker-user=${{ secrets.PRIVATE_DOCKER_HUB_USERNAME }} 
          --private-docker-token=${{ secrets.PRIVATE_DOCKER_HUB_ACCESS_TOKEN }} 
          --github-user=${{ github.actor }}
