name: Deploy to IBM Cloud And Execute Enrichment Tests

on:
#  release:
#    types: [created]
  pull_request:
    branches: [ main ]

# Environment variables available to all jobs and steps in this workflow
env:
  GITHUB_SHA: ${{ github.sha }}
  IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
  IBM_CLOUD_REGION: us-east
  # Create a unique test namespace name
  CLUSTER_NAMESPACE: github-${RANDOM}
  FHIR_IP: $CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com/fhir
  FHIR_DEID_IP: $CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com/fhir-deid
  ASCVD_FROM_FHIR_IP: $CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com/ascvd-from-fhir
  TERM_PREP_IP: $CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com/term-services-prep
  DEID_PREP_IP: $CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com/deid-prep
  DEFAULT_PASSWORD: integrati0n
  
  # Create the VPC Global Load Balancer specific to the health-patterns-1 cluster and save the GLB ID
  json: '{"name" : "$CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com",
         "fallback_pool" : "64c39c1c0638d539cae6d5ff593a0493", 
         "default_pools" :["64c39c1c0638d539cae6d5ff593a0493"], 
         "ttl" : 1, 
         "proxied" : true, 
         "session_affinity" : "cookie"}'
  TEMP_ID: (ibmcloud cis glb-create 6ff29db14b24b78a36227f49e18f3177 --json ${json} -i "Cloud Internet Services - Health Patterns" | grep ID)
  TEST_GLB_ID: ${TEMP_ID:23}

jobs:
  deploy:
    name: Deploy Health Patterns Chart to the IBM Cloud
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # Download and Install IBM Cloud CLI
    - name: Install IBM Cloud CLI
      run: |
        curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
        ibmcloud --version
        ibmcloud config --check-version=false
        ibmcloud plugin install -f kubernetes-service

    # Authenticate with IBM Cloud CLI
    - name: Authenticate into IBM Cloud Integration Squad Kubernetes Cluster
      run: |
        ibmcloud login --apikey "${IBM_CLOUD_API_KEY}" -r "${IBM_CLOUD_REGION}" -g dev-env-wdc-kube
        ibmcloud ks cluster config --cluster health-patterns-1

    
    # Setup and Install Chart 
    - name: Install Chart
      run: |
        kubectl create namespace $CLUSTER_NAMESPACE
        kubectl config current-context
        kubectl config set-context --current --namespace=${CLUSTER_NAMESPACE}
        helm dependency update helm-charts/health-patterns
        sed -i -e "s/\&hostname replace-me/\&hostname $CLUSTER_NAMESPACE.wh-health-patterns.dev.watson-health.ibm.com/g" helm-charts/health-patterns/values.yaml
        helm install ingestion helm-charts/health-patterns  -f helm-charts/health-patterns/clinical_ingestion.yaml --set ascvd-from-fhir.ingress.enabled=true --set deid-prep.ingress.enabled=true --set term-services-prep.ingress.enabled=true --wait --timeout 6m0s
        kubectl get all

    # Build Enrichment Tests 
    - name: Build Tests
      run: |
         cd clinical-enrichment
         echo "*************************************" 
         echo "* Build the testcases               *"
         echo "*************************************"
         mvn clean install -e -Dip.fhir=$FHIR_IP -Dport.fhir=$FHIR_PORT -Dip.fhir.deid=$FHIR_DEID_IP -Dport.fhir.deid=$FHIR_DEID_PORT -Dip.deid.prep=$DEID_PREP_IP -Dport.deid.prep=$DEID_PREP_PORT -Dip.term.prep=$TERM_PREP_IP -Dport.term.prep=$TERM_PREP_PORT -Dip.ascvd.from.fhir=$ASCVD_FROM_FHIR_IP -Dport.ascvd.from.fhir=$ASCVD_FROM_FHIR_PORT -Dpw=$DEFAULT_PASSWORD
         echo "*************************************" 
         echo "* Properties File:                  *"
         echo "*************************************"
         cat src/test/resources/enrich-flow.properties
         
    # Execute Enrichment Tests 
    - name: Execute Tests
      run: |
         echo "*************************************"
         echo "* Waiting for 1 minute              *"
         echo "*************************************"
         date
         sleep 60  
         date
         cd clinical-enrichment
         echo "*************************************" 
         echo "* Execute the testcases             *"
         echo "*************************************"
         mvn -e -DskipTests=false -Dtest=BasicEnrichmentTests test
         mvn -e -DskipTests=false -Dtest=EnrichmentConfigTests test
         mvn -e -DskipTests=false -Dtest=ASCVDEnrichmentTests test
      

    # Uninstall Chart
    - name: Uninstall Chart
      run: helm uninstall ingestion
           kubectl delete namespace $CLUSTER_NAMESPACE
           ibmcloud cis glb-delete 64c39c1c0638d539cae6d5ff593a0493 $TEST_GLB_ID
      if: ${{ always() }}
