name: nlp-insights PUSH Validation
on: 
  push:
    paths:
    - 'services/nlp-insights/**'
    - '.github/**'
defaults:
  run:
    shell: bash
    working-directory: services/nlp-insights

jobs:
  job:
    name: Build nlp-insights
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup 
      run: |
           sudo apt install python3.9
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
           sudo update-alternatives --set python3 /usr/bin/python3.9
           sudo pip3 install -U pip
           npm install -g dockerlint
    - name: Unit Test 
      run: ./gradlew test 

    - name: Static Code Analysis
      run: |
           MESSAGE=$(git log -1 HEAD --pretty=format:%s)
           if [[ "$MESSAGE" == *\[noFailForSourceProblems\]* ]]; then
             CHECK_SOURCE_NO_FAIL="-PnoFailForSourceProblems"
           fi
           ./gradlew checkSource $CHECK_SOURCE_NO_FAIL

    - name: Docker Lint
      run: dockerlint

    - name: Save Artifiacts
      uses: actions/upload-artifact@v2
      with:
        name: nlp-insights-tests
        path: ./services/nlp-insights/build/reports
      
        #    - name: Docker build
        # if: ${{contains( steps.filecheck.outputs.changed_files, 'services/nlp-insights')}}
        #run: |
        #   .github/workflows/scripts/build-nlp-insights-docker.sh \
        #   -s=nlp-insights \
        #   -m=${{github.event_name}} \
        #   --docker-user=${{ secrets.DOCKER_HUB_USERNAME }} \
        #   --docker-token=${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} 





