name: nlp-insights push docker image 
on: 
  workflow_dispatch:
    inputs:
      username:
        description: 'docker login'
        required: true
      password:
        description: 'docker user password'
        required: true
      org:
        description: 'docker organization'
        required: true
        default: 'alvearie'
      repo:
        description: 'docker repository'
        required: true
        default: 'nlp-insights'
      server:
        description: 'server'
        required: true
        default: 'docker.io'
      version:
        description: 'image version tag'
        required: true
defaults:
  run:
    shell: bash
    working-directory: services/nlp-insights

jobs:
  job:
    name: Push nlp-insights docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup 
      run: |
           sudo apt install python3.9
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
           sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2
           sudo update-alternatives --set python3 /usr/bin/python3.9
           sudo pip3 install -U pip
      
    - name: Docker login
      run: |
              password = ${{ github.event.inputs.password }}
              echo "::add-mask::$password"
              echo $password | docker login --username ${{ github.event.inputs.username }} --password-stdin ${{ github.event.inputs.server }}
    - name: Docker build
      run:  ./gradlew docker -PdockerUser=${{ github.event.inputs.org }}/${{ github.event.inputs.repo }} -Pversion=${{ github.event.inputs.version }}
    - name: Docker push
      run:  ./gradlew dockerPush -PdockerUser=${{ github.event.inputs.org }}/${{ github.event.inputs.repo }} -Pversion=${{ github.event.inputs.version }}






