{{- if .Values.ingress.enabled -}}
{{- $ingressPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ascvd-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ascvd.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
spec:
  rules:
    - host: {{ .Release.Namespace }}.ascvd.{{ .Values.ingress.subdomain }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Release.Name }}-ascvd
                port: 
                  number: {{ $ingressPort }}
{{- end }}